sudo: required
language: node_js
node_js:
  - '6'
services:
  - docker
before_install:
  - pip install --user awscli
  - npm install
  - docker build -t $AWS_IMAGE_TAG .
script:
  - export MY_LOGIN="$(aws ecr get-login)"
  - $MY_LOGIN
  - docker tag $AWS_IMAGE_TAG $AWS_ECR_REPOSITORY/$AWS_IMAGE_TAG
  - docker push $AWS_ECR_REPOSITORY/$AWS_IMAGE_TAG
after_script:
  - cd post-process
  - npm install
  - node index.js --cluster=$AWS_CLUSTER
