sudo: required
language: node_js
node_js:
  - '6'
services:
  - docker
before_install:
  - pip install --user awscli
  - npm install
  - docker build -t MAGICJS .
script:
  - export MY_LOGIN="$(aws ecr get-login)"
  - $MY_LOGIN
  - docker tag MAGICJS $AWS_ECR_REPOSITORY/MAGICJS
  - docker push $AWS_ECR_REPOSITORY/MAGICJS
after_script:
  - cd post-process
  - npm install
  - node index.js --cluster=$AWS_CLUSTER
