sudo: required
language: node_js
node_js:
  - '6'
services:
  - docker
before_install:
  - pip install --user awscli
  - npm install
  - docker build -t $IMAGE_NAME .
script:
  - export MY_LOGIN="$(aws ecr get-login)"
  - $MY_LOGIN
  - docker tag $IMAGE_NAME $AWS_ECR_REPOSITORY/$IMAGE_NAME
  - docker push $AWS_ECR_REPOSITORY/$IMAGE_NAME
after_script:
  - cd post-process
  - npm install
  - node index.js --cluster=$AWS_CLUSTER
